-- 코드를 입력하세요
-- SELECT *
-- FROM PRODUCT

-- SELECT *
-- FROM OFFLINE_SALE

SELECT P.PRODUCT_CODE, SUM(P.PRICE * SALES_AMOUNT) AS COUNT
FROM PRODUCT P
INNER JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE   -- 상품 코드별 매출액의 합계
ORDER BY COUNT DESC, P.PRODUCT_CODE ASC 