-- 코드를 입력하세요

-- 테이블에서 평균 대여 기간이 7일 이상인 자동차들의
-- 자동차 ID와 평균 대여 기간(컬럼명: AVERAGE_DURATION) 리스트를 출력


-- SELECT CAR_ID, ROUND(SUM(TRUNC(END_DATE - START_DATE + 1))/COUNT(*), 1) AS AVERAGE_DURATION
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY CAR_ID
-- HAVING ROUND(SUM(TRUNC(END_DATE - START_DATE + 1))/COUNT(*), 1) >= 7
-- ORDER BY AVERAGE_DURATION DESC, TO_NUMBER(CAR_ID) DESC



SELECT CAR_ID, TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM9990.0') AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
ORDER BY TO_NUMBER(AVERAGE_DURATION) DESC, CAR_ID DESC