-- 코드를 입력하세요
-- ** 외래키
-- 아직 입양을 못 간 동물 중, -> outs 가 null 
-- 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일을 조회
-- SELECT * FROM ANIMAL_INS
-- SELECT * FROM ANIMAL_OUTS
-- '''
-- SELECT * 
-- FROM ANIMAL_INS I 
-- LEFT JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE O.ANIMAL_ID IS NULL
-- ORDER BY I.DATETIME
-- '''

SELECT *
FROM ( 
    SELECT I.NAME, I.DATETIME
    FROM ANIMAL_INS I 
    LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY I.DATETIME
)
WHERE ROWNUM <= 3
